/**
 * Product slugs that have images in public/images/products/.
 * Generated by: npm run generate:image-manifest
 * Products not in this set show the illustration (vial SVG + label) instead.
 */
export const PRODUCT_IMAGE_SLUGS = new Set(["glp-1-semaglutide","glp-1-tirzepatide","glp-1-retatrutide","survodutide","tesofensine","aod-9604","sermorelin","tesamorelin","ipamorelin","cjc-1295-no-dac","ghrp-2","ghrp-6","hexarelin","igf-1-lr3","mgf","peg-mgf","follistatin-344","blend-cjc-ipamorelin","blend-tesamorelin-ipamorelin-10","blend-tesamorelin-ipamorelin-15","blend-3x-tesamorelin-ipamorelin-mgf","blend-4x-tesamorelin-ipamorelin-ghrp2-mgf","bpc-157","tb500","wolverine-stack","glow-42","glow-50","glow-70","klow-80","ghk-cu","kpv","cartalax","cardiogen","ll-37","ll-37-complex","curcumin","pnc-28","hcg","gonadorelin","kisspeptin","pt-141","epitalon","mots-c","dsip","oxytocin"]);
